// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package person

import (
	"database/sql"
)

type Department struct {
	DepartmentID   int32
	DepartmentName string
}

type Employee struct {
	EmployeeID   int32
	EmployeeName string
	DepartmentID sql.NullInt32
}
